Test build for #3034

diff --git a/python-3.12-image/Dockerfile b/python-3.12-image/Dockerfile
--- a/python-3.12-image/Dockerfile
+++ b/python-3.12-image/Dockerfile
@@ -25,6 +25,8 @@ FROM registry.suse.com/bci/bci-base:15.6
 
 RUN set -euo pipefail; \
     zypper -n install --no-recommends python312-devel python312 python312-pip curl findutils gawk git-core procps python312-pipx lifecycle-data-sle-module-python3 lifecycle-data-sle-module-development-tools
+
+# cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n clean -a; \
     rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
     rm -rf {/target,}/run/*; \
@@ -33,6 +35,8 @@ RUN set -euo pipefail; zypper -n clean -a; \
     rm -f {/target,}/var/cache/ldconfig/aux-cache; \
     command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
 
+# set the day of last password change to empty
+RUN set -euo pipefail; sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/' /etc/shadow
 
 # Define labels according to https://en.opensuse.org/Building_derived_containers
 # labelprefix=com.suse.bci.python
