🤖: Update build recipes from templates

diff --git a/kiwi-image/Dockerfile b/kiwi-image/Dockerfile
--- a/kiwi-image/Dockerfile
+++ b/kiwi-image/Dockerfile
@@ -27,6 +27,8 @@ FROM registry.suse.com/bci/bci-base:15.7
 
 RUN set -euo pipefail; \
     zypper -n install --no-recommends checkmedia dracut-kiwi-oem-repart enchant-devel gcc glibc-devel iproute2 java-21-openjdk-headless jing kiwi-systemdeps-filesystems kpartx libxml2-devel lvm2 make netcat-openbsd python3-devel python3-kiwi python3-pip systemd-default-settings-branding-SLE tack timezone xorriso xz sles-release curl findutils gawk git-core procps
+
+# cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n clean -a; \
     rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
     rm -rf {/target,}/run/*; \
@@ -35,6 +37,8 @@ RUN set -euo pipefail; zypper -n clean -a; \
     rm -f {/target,}/var/cache/ldconfig/aux-cache; \
     command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
 
+# set the day of last password change to empty
+RUN set -euo pipefail; sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/' /etc/shadow
 
 # Define labels according to https://en.opensuse.org/Building_derived_containers
 # labelprefix=com.suse.bci.kiwi
diff --git a/rust-stable-image/Dockerfile b/rust-stable-image/Dockerfile
--- a/rust-stable-image/Dockerfile
+++ b/rust-stable-image/Dockerfile
@@ -19,14 +19,16 @@
 #!BuildTag: bci/rust:stable
 #!BuildTag: bci/rust:%%RUST_VERSION%%-1.%RELEASE%
 #!BuildTag: bci/rust:%%RUST_VERSION%%
-#!BuildTag: bci/rust:1.89
+#!BuildTag: bci/rust:1.90
 #!BuildTag: bci/rust:latest
 #!BuildName: bci-rust-stable
-#!BuildVersion: 15.7.1.89.1
+#!BuildVersion: 15.7.1.90.1
 FROM registry.suse.com/bci/bci-base:15.7
 
 RUN set -euo pipefail; \
-    zypper -n install --no-recommends rust1.89 cargo1.89 lifecycle-data-sle-module-development-tools
+    zypper -n install --no-recommends rust1.90 cargo1.90 lifecycle-data-sle-module-development-tools
+
+# cleanup logs and temporary files
 RUN set -euo pipefail; zypper -n clean -a; \
     rm -rf {/target,}/var/log/{alternatives.log,lastlog,tallylog,zypper.log,zypp/history,YaST2}; \
     rm -rf {/target,}/run/*; \
@@ -35,12 +37,14 @@ RUN set -euo pipefail; zypper -n clean -a; \
     rm -f {/target,}/var/cache/ldconfig/aux-cache; \
     command -v zypper >/dev/null 2>&1 || rm -f /var/lib/zypp/AutoInstalled
 
+# set the day of last password change to empty
+RUN set -euo pipefail; sed -i 's/^\([^:]*:[^:]*:\)[^:]*\(:.*\)$/\1\2/' /etc/shadow
 
 # Define labels according to https://en.opensuse.org/Building_derived_containers
 # labelprefix=com.suse.bci.rust
 LABEL org.opencontainers.image.authors="https://github.com/SUSE/bci/discussions"
-LABEL org.opencontainers.image.title="SLE BCI Rust 1.89"
-LABEL org.opencontainers.image.description="Rust 1.89 container based on the SLE Base Container Image."
+LABEL org.opencontainers.image.title="SLE BCI Rust 1.90"
+LABEL org.opencontainers.image.description="Rust 1.90 container based on the SLE Base Container Image."
 LABEL org.opencontainers.image.version="%%RUST_VERSION%%"
 LABEL org.opencontainers.image.url="https://www.suse.com/products/base-container-images/"
 LABEL org.opencontainers.image.created="%BUILDTIME%"
@@ -50,7 +54,7 @@ LABEL org.opencontainers.image.ref.name="%%RUST_VERSION%%-1.%RELEASE%"
 LABEL org.opensuse.reference="registry.suse.com/bci/rust:%%RUST_VERSION%%-1.%RELEASE%"
 LABEL org.openbuildservice.disturl="%DISTURL%"
 LABEL com.suse.supportlevel="l3"
-LABEL com.suse.supportlevel.until="2025-11-20"
+LABEL com.suse.supportlevel.until="2026-01-01"
 LABEL com.suse.eula="sle-bci"
 LABEL com.suse.lifecycle-url="https://www.suse.com/lifecycle#suse-linux-enterprise-server-15"
 LABEL com.suse.release-stage="released"
