vc-command: run variable extraction & changelog creation in one step
For some reason github does not persist the environment variables in this
workflow, so we just do everything in one step.

diff --git a/.github/workflows/vc-command.yml b/.github/workflows/vc-command.yml
--- a/.github/workflows/vc-command.yml
+++ b/.github/workflows/vc-command.yml
@@ -8,24 +8,6 @@ jobs:
   append-changelog:
     runs-on: ubuntu-latest
     steps:
-      - name: Get the necessary variables from the command
-        id: vars
-        run: |
-          # this returns SUSE:$branch_name
-          branch="${{ github.event.client_payload.pull_request.head.label }}"
-          if [[ -z "$branch" ]]; then echo "No branch set!"; exit 1; fi
-          # fail if the origin branch is wrong
-          [[ "$branch" =~ ^SUSE:for-deploy- ]]
-          echo "os_version=${branch/SUSE:for-deploy-/}" >> $GITHUB_OUTPUT
-
-          user="${{ github.event.client_payload.slash_command.args.named.user }}"
-          if [[ -z "$user" ]]; then echo "Missing user parameter!"; exit 1; fi
-          echo "user=$user" >> $GITHUB_OUTPUT
-
-          entry="${{ github.event.client_payload.slash_command.args.unnamed.all }}"
-          if [[ -z "$entry" ]]; then echo "No changelog entry provided!"; exit 1; fi
-          echo "entry=$entry" >> $GITHUB_OUTPUT
-
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
@@ -48,12 +30,28 @@ jobs:
       - name: install python dependencies
         run: poetry install
 
-      - name: add the changelog entries
+      - name: Add the changelog entries
+        id: vars
         run: |
+          # this returns SUSE:$branch_name
+          branch="${{ github.event.client_payload.pull_request.head.label }}"
+          if [[ -z "$branch" ]]; then echo "No branch set!"; exit 1; fi
+          # fail if the origin branch is wrong
+          [[ "$branch" =~ ^SUSE:for-deploy- ]]
+          export OS_VERSION="${branch/SUSE:for-deploy-/}"
+
+          user="${{ github.event.client_payload.slash_command.args.named.user }}"
+          if [[ -z "$user" ]]; then echo "Missing user parameter!"; exit 1; fi
+          export user
+
+          entry="${{ github.event.client_payload.slash_command.args.unnamed.all }}"
+          if [[ -z "$entry" ]]; then echo "No changelog entry provided!"; exit 1; fi
+          export entry
+
           packages="${{ github.event.client_payload.slash_command.args.named.packages }}"
           if [[ -z "$packages" ]]; then unset packages; fi
+
           poetry run ./scratch-build-bot.py -vvvv add_changelog_entry
         env:
           OSC_PASSWORD: ${{ secrets.OSC_PASSWORD }}
           OSC_USER: "defolos"
-          OS_VERSION: ${{ env.os_version }}
